### ISSUE TITLE
Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.PasswordSchema)

### ISSUE THREAD

**Issue by tomasherman** [guardrail-dev/guardrail#255] opened 2019-04-26 08:25 UTC
**Update** This issue is tracking errors generated by following schemas:

```yaml
swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
definitions:
  Foo:
    type: object
    properties:
      somePassword:
        type: string
        format: password
      someFile:
        type: file
      someBinary:
        type: string
        format: binary
```

They all generate errors similar to this one:
```
Error: Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.PasswordSchema):
  class PasswordSchema {
      class Schema {
      }
      type: string
      format: password
  }
```

----

Original issue:

Hi,

when using follwing definition:
```json
{"password":{"format":"password","type":"string"}}
```

I get the following error:
```
Error: Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.PasswordSchema):
  class PasswordSchema {
      class Schema {
      }
      type: string
      format: password
  }
```

Any idea what to do about it? I suspect it's a format that has been removed in swagger v3 or something like that

**Comment by tomasherman** [comment] 2019-04-26 11:15
Ok i think i figured it out for password (see #256 ) ... but i have same problem with `type: file`, which is trickier ... i'm not sure how to handle that one

**Comment by tomasherman** [comment] 2019-04-26 11:57
this is an example of the offending yml...
```yml
get:
  summary: get timezone data
  operationId: getTimezoneData
  description: |-
    Get timezone data (also called tzdata)
  responses:
    200:
      description: Succesfully retrieved tzdata.
      schema:
        description: User specific tzdata file.
        type: file
```

i assume raw response could be used for this but this fails the compilation ... i wonder how to solve this ... perhaps generate response that takes `fs2` stream and pipe it to raw response in the generated code?

**Comment by kelnos** [comment] 2019-04-26 18:47
What's the compiler error?  We've supported `type: file` for some time now; not sure why it wouldn't work.

**Comment by blast-hardcheese** [comment] 2019-04-26 23:28
@tomasherman akka-http has support for `type: file`, not sure that http4s has support for that yet. The naive implementation in akka-http uses a helper method to build a `java.io.File` object, which the file is streamed into.

This isn't a great solution though, I'd much rather go with something `InputStream` based to stream into a file or to anything else that can behave like an `InputStream`.

**Comment by tomasherman** [comment] 2019-04-29 07:39
Like i said, the error comes up during generaetion phase:
```
Error: Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.PasswordSchema):
  class PasswordSchema {
      class Schema {
      }
      type: string
      format: password
  }
```

**Comment by blast-hardcheese** [comment] 2019-05-01 06:25
This is likely related to
[SwaggerGenerator.scala#L103-L111](https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala#L103-L111):
```scala
      case GetType(model) =>
        val determinedType = Option(model.getType()).fold("No type definition")(s => s"type: $s")
        val className      = model.getClass.getName
        Target.fromOption(
          Option(model.getType()),
          s"""|Unknown type for the following structure (${determinedType}, class: ${className}):
              |  ${model.toString().lines.filterNot(_.contains(": null")).mkString("\n  ")}
              |""".stripMargin
        )
```
where `.getType()` returns `null`, as it should be `.getSchema().getType()`. I wonder why they embed a `Schema[_]` into a `FileSchema`... this seems unnecessary.

Could you try using an OpenAPI 3.x spec to reproduce?

Alternately, I'm realizing that we don't have any tests for `type: file` in the response structure, which would indicate why this hasn't come up before.

**Comment by tomasherman** [comment] 2019-05-01 09:12
i can provide some failing test case, but is there any chance any of you guys could take a stab at this? I am already battling in two other merge requests and i don't have any more time to invest :(

**Comment by blast-hardcheese** [comment] 2019-05-01 14:45
I can't promise I can get to it this week, unfortunately. Thank you for your efforts iterating on your other PRs, by the way :smile:

**Comment by tomasherman** [comment] 2019-05-01 14:48
well, we either have to make it work for our use cases, or use python at work ... so not really much choice :D but thanks for the guidance ... i might get to it after all, i think i made good progress on the other PRs

**Comment by Gipetto** [comment] 2019-05-01 20:01
Another failure example, if it helps, otherwise this just a self-serving +1 to having the same issue.

```yaml
      responses:
        '200':
          description: OK
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
```

Produces the error:

```
[ERROR] Error: Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.BinarySchema):
  class BinarySchema {
      class Schema {
      }
      type: string
      format: binary
  }

[ERROR] Failed to generate client
com.twilio.maven.swagger.CodegenFailedException
    at com.twilio.maven.swagger.AbstractSwaggerCodegenMojo.$anonfun$guardrailTwilioTask$4 (AbstractSwaggerCodegenMojo.scala:131)
```

**Comment by tomasherman** [comment] 2019-05-05 18:00
I wonder how `type string` `format binary` should be represented...it seems the easiest solution would be Array[Byte] but i feel `Stream[Byte]` would be better as these files will probably always be files or something that might be quite large

**Comment by tomasherman** [comment] 2019-05-05 18:59
@Gipetto i believe i patched this issue with #283 but i think further improvements on how binary properties should be handled are in order

**Comment by rethab** [comment] 2019-08-09 09:08
There's a similar issue with the format type `email`. I don't think this one requires special handling (see https://swagger.io/specification/#data-types) but it is also not disallowed.

**Comment by nick-bauer** [comment] 2019-12-26 21:40
I am running into a similar issue with type: array

"FooBatch": {
        "properties": {
          "foos": {
            "items": {
              "$ref": "#/components/schemas/Foo"
            },
            "type": "array"
          }
        }
      }

[31mError:[0mUnknown type for the following structure (No type definition, class: io.swagger.v3.oas.models.media.Schema):
  class Schema {
      properties: {foos=class ArraySchema {
          class Schema {
          }
          type: array
          items: class Schema {
              $ref: #/components/schemas/Foo
          }
      }}
  }

**Comment by blast-hardcheese** [comment] 2019-12-27 02:53
@nick-bauer: What's the context around `FooBatch`? Where in the document is it coming from?

**Comment by blast-hardcheese** [comment] 2020-06-05 00:51
Following up, as this bit one of my coworkers -- It turns out that the assumption of `type: array` with an `items` that doesn't have a definite `type` can cause this error.

**Comment by blast-hardcheese** [comment] 2022-02-20 07:31
#1407 improves the situation referred to by @nick-bauer -- I unified the different type transformation logic, which was causing issues with `$refs` inside of `array`.

Closing this, thank you 🙂

**Closed by blast-hardcheese** 2022-02-20 07:31 UTC
Labels: bug, help wanted
