### ISSUE TITLE
Uppercase letters in object field name generate incorrect field name in class.

### ISSUE THREAD

**Issue by meloniasty** [guardrail-dev/guardrail#814] opened 2020-10-16 20:12 UTC
Hi, I updated sbt-guardrail in my project from 0.58.1.1 to 0.61.0.1.

I have specification which contains fields with uppercased letters i.e. `fieldABC`

In old version (0.58...) plugin generated case class with name as above

But in new version (0.61..) it generate name `fieldAbc`

Is there any swagger or guardrail property to tell how field should looks like?

I need field with uppercase name.

**Comment by kelnos** [comment] 2020-10-16 21:55
Recently we updated the name transformation code to generate more consistent names.  The names aren't always the best, most idiomatic name, but they're mostly close, and they're better than before (on average), and are at least consistent.

I suggest you post the generated code here to illustrate what you're asking, but I'll take a guess first: I suspect you might be misinterpreting what's happening under the covers.  Even though the field name in the case class is `fieldAbc`, if you've specified `fieldABC` in the OpenAPI spec, `fieldABC` will still be what is used in the JSON that's sent/received over the network.

**Comment by meloniasty** [comment] 2020-10-17 14:31
my openapi definition is:

```
openapi: 3.0.1
info:
  title: Test
  version: v1
paths:
#  /test:
#    summary: test path
components:
  schemas:
    JohnDoe:
      type: object
      properties:
        id:
          type: integer
        fieldABC:
          type: string

```

if I use `addSbtPlugin("com.twilio"        % "sbt-guardrail"       % "0.58.1.1")`

generated model is:

```
/*
 * This file was generated by Guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package it.impossible.model.definitions
import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import io.circe.generic.semiauto._
import cats.implicits._
import _root_.it.impossible.model.Implicits._
case class JohnDoe(id: Option[BigInt] = None, fieldABC: Option[String] = None)
object JohnDoe {
  implicit val encodeJohnDoe: Encoder.AsObject[JohnDoe] = {
    val readOnlyKeys = Set[String]()
    Encoder.AsObject.instance[JohnDoe](a => JsonObject.fromIterable(Vector(("id", a.id.asJson), ("fieldABC", a.fieldABC.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeJohnDoe: Decoder[JohnDoe] = new Decoder[JohnDoe] { final def apply(c: HCursor): Decoder.Result[JohnDoe] = for (v0 <- c.downField("id").as[Option[BigInt]]; v1 <- c.downField("fieldABC").as[Option[String]]) yield JohnDoe(v0, v1) }
}
```


if I use `addSbtPlugin("com.twilio"        % "sbt-guardrail"       % "0.61.0.1")`

generated class is:

```
/*
 * This file was generated by guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package it.impossible.model.definitions
import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.it.impossible.model.Implicits._
case class JohnDoe(id: Option[BigInt] = None, fieldAbc: Option[String] = None)
object JohnDoe {
  implicit val encodeJohnDoe: Encoder.AsObject[JohnDoe] = {
    val readOnlyKeys = Set[String]()
    Encoder.AsObject.instance[JohnDoe](a => JsonObject.fromIterable(Vector(("id", a.id.asJson), ("fieldABC", a.fieldAbc.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeJohnDoe: Decoder[JohnDoe] = new Decoder[JohnDoe] { final def apply(c: HCursor): Decoder.Result[JohnDoe] = for (v0 <- c.downField("id").as[Option[BigInt]]; v1 <- c.downField("fieldABC").as[Option[String]]) yield JohnDoe(v0, v1) }
}
```


so the main difference is that in first case i have JohnDoe with `fieldABC` and the second is JohnDoe with `fieldAbc`


so then if I use generated class as model in service which is playframework with play-json as decoding json
```
{"id":1, "fieldABC":"Test"}
```
does not work.


is there any simple solution for sbt-guardrail "0.61.0.1" to generate model class definitions with fields names the same as in openapi yml file (no matter if it's a good name or not :) )?

**Comment by kelnos** [comment] 2020-10-18 03:57
I'm not sure why that JSON example you mentioned would not work; if you look at the generated decoder (reformatted for better readability):
```scala
implicit val decodeJohnDoe: Decoder[JohnDoe] = new Decoder[JohnDoe] {
  final def apply(c: HCursor): Decoder.Result[JohnDoe] =
    for {
      v0 <- c.downField("id").as[Option[BigInt]]
      v1 <- c.downField("fieldABC").as[Option[String]]
    } yield JohnDoe(v0, v1)
}
```
Note that it does indeed use `"fieldABC"` as the field name.  And when I use it from the scala console, using your test JSON string, it works:
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
case class JohnDoe(id: Option[BigInt] = None, fieldABC: Option[String] = None)
object JohnDoe {
  implicit val encodeJohnDoe: Encoder.AsObject[JohnDoe] = {
    val readOnlyKeys = Set[String]()
    Encoder.AsObject.instance[JohnDoe](a => JsonObject.fromIterable(Vector(("id", a.id.asJson), ("fieldABC", a.fieldABC.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeJohnDoe: Decoder[JohnDoe] = new Decoder[JohnDoe] { final def apply(c: HCursor): Decoder.Result[JohnDoe] = for (v0 <- c.downField("id").as[Option[BigInt]]; v1 <- c.downField("fieldABC").as[Option[String]]) yield JohnDoe(v0, v1) }
}

// Exiting paste mode, now interpreting.

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
defined class JohnDoe
defined object JohnDoe

scala> import io.circe.parser._
import io.circe.parser._

scala> decode[JohnDoe]("""{"id":1, "fieldABC":"Test"}""")
res0: Either[io.circe.Error,JohnDoe] = Right(JohnDoe(Some(1),Some(Test)))
```

Just to reiterate: the case class member names do not have to be the same as the field names, as we define the circe encoder/decoder explicitly (using the field name exactly as specified in the openapi spec file), without using auto or semiauto derivation.

I'm not sure why it's not working for you within the play framework; I'm not sure that we've tried to use these classes with play, so there may be some other issue with how play tries to make use of the generated case classes.  My understanding is that play does not use circe by default, so if it is trying to auto-derive encoders/decoders for case classes, using a different JSON library, that will not work (and you've just been lucky so far in previous versions that the generated names in the case classes happened to match what was in your spec).

**Comment by meloniasty** [comment] 2020-10-18 14:29
to be sure, problem is with sbt-guardrail 0.61.0.1 and play-json library
(with circe-json it works)


main problem is that plugin generates case class with changed field names from openapi definition (and yes I can imagine that name convention is not easy)


so main question would be is there possibility to use new plugin  that will generate classes with exactly the same field names as in openapi definition? :)
(if not I'll be using old 0.58 sbt-guardrail)

**Comment by blast-hardcheese** [comment] 2020-10-18 18:20
@meloniasty Our attempt has been to normalize field names to JVM field naming conventions from the beginning, with increasing accuracy as time goes on. To @kelnos' point earlier, even with 0.58.x you _may_ just be getting lucky, guardrail does not rely on macro-reflection for any generated code, the introduction of macro-reflecting encoders and decoders is explicitly not a feature we've attempted to offer.

Googling around, there are projects like [`play-circe`](https://github.com/jilen/play-circe) that seem to offer something that would address your need.

There may additionally be a library that exposes the very narrow source API from circe that we actually use, namely around `Decoder`/`Encoder` class' `forProductN` helper functions, and possibly the `jawn` parser. If you do not intend to use circe anywhere else in your project, it may be possible to replicate the public circe API, but then adapting that to play-json.

A more sustainable solution would be to actually add proper support for `play-json` as an alternative to circe, possibly even as an inroads to generating Play route generators. I've tried to keep most of the circe-isms located directly in [`CirceProtocolGenerator`](https://github.com/twilio/guardrail/blob/de3c9af067c08a612994895b0e10e1a52cda3e79/modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala), explicitly with the intention of other JSON generators to be supported in the future.

Hopefully this paints a broader picture as far as options go moving forward, I'd like to not alienate Play! users if at all possible, though supporting field-name-reflection is explicitly not a goal of guardrail, as it is not reliable at scale.

Please let us know if you'd like more advice in any of these directions, I'd be happy to provide some more guidance or motivation for anything I've specified here.

**Comment by meloniasty** [comment] 2020-10-19 06:48
@blast-hardcheese, @kelnos  thanks!
I thought that there is some toggle for my problem :D

yes, I know `play-circe` maybe I'll investigate in the future more

I also have tests for my contract jsons -  encoding/decoding - so till now one problematic case is one described here.
fields with uppercase letters are my legacy :) so I need to work with it 

anyway, everything is clear for me now, thank you

**Comment by kelnos** [comment] 2021-06-03 07:03
ok, seems like this was just some confusion around how the generated classes are intended to be used.  going to close this for now, please reopen if the issue is still present when circe is used.

**Closed by kelnos** 2021-06-03 07:03 UTC
