### ISSUE TITLE
JSON body param with embedded schema generates FormData

### ISSUE THREAD

**Issue by sbrunk** [guardrail-dev/guardrail#313] opened 2019-05-28 08:57 UTC
Given the following spec with an embedded schema for the in body, Guardrail generates a client method (see below) that takes `name` and `body` and uses them as form parameters. It also takes a `body: io.circe.Json` which is ignored.

This could be related to #237, but since we're consuming JSON here, the form params seem definitely wrong here. It also clashes with the `name` path parameter.

As soon as I move the schema into a definition and reference that, everything works fine.

Ideally, Guardrail would generate a case class and codecs for the embedded schema (perhaps using the `name` field for the class name?). At least it should not create form params but just use the JSON body instead.

```yaml
swagger: '2.0'
info:
  title: JupyterHub
  description: The REST API for JupyterHub
produces:
  - application/json
consumes:
  - application/json
paths:
  /users/{name}:
    patch:
      operationId: changeUser
      summary: Modify a user
      description: Change a user's name or admin status
      parameters:
        - name: name
          description: username
          in: path
          required: true
          type: string
        - name: data
          in: body
          required: true
          description: Updated user info. At least one key to be updated (name or admin) is required.
          schema:
            type: object
            properties:
              name:
                type: string
                description: the new name (optional, if another key is updated i.e. admin)
              admin:
                type: boolean
                description: update admin (optional, if another key is updated i.e. name)
      responses:
        '200':
          description: The updated user info
```

```scala
  def changeUser(name: String, name: String, admin: Boolean, body: io.circe.Json, headers: List[HttpHeader] = Nil): EitherT[Future, Either[Throwable, HttpResponse], ChangeUserResponse] = {
    val allHeaders = headers ++ scala.collection.immutable.Seq[Option[HttpHeader]]().flatten
    makeRequest(HttpMethods.PATCH, host + basePath + "/users/" + Formatter.addPath(name), allHeaders, FormData(List(List(("name", Formatter.show(name))), List(("admin", Formatter.show(admin)))).flatten: _*), HttpProtocols.`HTTP/1.1`).flatMap(req => EitherT(httpClient(req).flatMap(resp => resp.status match {
      case StatusCodes.OK =>
        resp.discardEntityBytes().future.map(_ => Right(ChangeUserResponse.OK))
      case _ =>
        FastFuture.successful(Left(Right(resp)))
    }).recover({
      case e: Throwable =>
        Left(Left(e))
    })))
  }
```

**Comment by sbrunk** [comment] 2019-05-28 11:52
I'd be happy too look into this but I guess I could use some hints where to start looking.

**Comment by blast-hardcheese** [comment] 2019-05-28 17:21
This is a duplicate of #76, let's continue the discussion there

**Comment by sbrunk** [comment] 2019-05-28 20:20
Independent of the more interesting general approach for nested object structures discussed in #76, I'd argue the form parameters and the ignored JSON body (see example) are a bug worth fixing, because based on the spec this clearly should be a JSON body and not `FormData`. What do you think?

**Comment by sbrunk** [comment] 2019-05-29 09:47
Seems like `extractParamsFromRequestBody` is resonsible for generating these form parameters, and does so even when we just consume `application/json`.

https://github.com/twilio/guardrail/blob/418ad1d23c5363677ae9dbb0bea18b09ff3b36f2/modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala#L126-L142

**Comment by blast-hardcheese** [comment] 2019-05-29 16:59
Completely missed that, I just focused on the `data: io.circe.Json`

I don't have time to review this until later this week, but this is definitely a separate bug from #76, as you've indicated.

**Closed** 2021-04-23 18:27 UTC
Labels: bug, core
